---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-gradle-pv-claim
  namespace: devops-tools
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
