apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-namespace
spec:
  selector:
    app: nginx-server
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 80
    - port: 443
      targetPort: 443
      nodePort: 443
