apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pv-claim
  namespace: nginx-namespace
spec:
  resources:
    requests:
      storage: 3Gi
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
